/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/app/**/*.{js,jsx,ts,tsx}",
    "./src/components/**/*.{js,jsx,ts,tsx}",
    "./src/features/**/*.{js,jsx,ts,tsx}",
    "./src/constants/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        background: "#F8FAFC",
        "background-dark": "#01161E",
        surface: "#FFFFFF",
        "surface-muted": "#F1F5F9",
        "primary-text": "#01161E",
        "secondary-text": "#475569",
        "rich-black": "#01161E",
        border: "#E2E8F0",
        primary: "#00F6EF",
        "primary-muted": "#CCFBFE",
        success: "#10B981",
        warning: "#F59E0B",
        danger: "#EF4444",
        info: "#00F6EF",
        "bg-dark": "#01161E",
        "surface-dark": "#0A1F2E",
        "surface-muted-dark": "#112B3A",
        "primary-text-dark": "#F0FDFF",
        "secondary-text-dark": "#7DD3D9",
        "border-dark": "#1E3A4A",
        "primary-dark": "#00F6EF",
        "primary-muted-dark": "#005A5E",
        "success-dark": "#34D399",
        "warning-dark": "#FBBF24",
        "danger-dark": "#F87171",
        "info-dark": "#00F6EF",
      },
      spacing: {
        px: "1px",
        0: "0px",
        0.5: "2px",
        1: "4px",
        1.5: "6px",
        2: "8px",
        2.5: "10px",
        3: "12px",
        3.5: "14px",
        4: "16px",
        5: "20px",
        6: "24px",
        7: "28px",
        8: "32px",
        9: "36px",
        10: "40px",
        11: "44px",
        12: "48px",
        14: "56px",
        16: "64px",
      },
      fontSize: {
        display: ["32px", { lineHeight: "40px" }],
        h1: ["28px", { lineHeight: "36px" }],
        h2: ["24px", { lineHeight: "32px" }],
        h3: ["20px", { lineHeight: "28px" }],
        body: ["16px", { lineHeight: "24px" }],
        small: ["14px", { lineHeight: "20px" }],
        caption: ["12px", { lineHeight: "16px" }],
      },
      borderRadius: {
        sm: "8px",
        md: "12px",
        lg: "16px",
        xl: "20px",
      },
    },
  },
  plugins: [],
};